import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './(components)/header';
import Footer from './(components)/footer';
import Auth from './(components)/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center">
        <Header />
        <Auth></Auth>
        {children}
        <Footer />
      </body>
    </html>
  );
}
